# workflows:
#   version: 2
#   build-test-and-deploy:
#     jobs:
#       - test
#       - buildAndPush
#           # requires:
#           #   - test
#       - deploy         
#           # requires:
#           #   - buildAndPush

version: 2.1

jobs:
  buildAndPush:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t siddokit/webapp:0.0.$CIRCLE_BUILD_NUM -t siddokit/webapp:latest -f ./WebApp/Dockerfile .
            echo $DOCKER_PWD|docker login -u $DOCKER_LOGIN --password-stdin
            docker push siddokit/webapp:0.0.$CIRCLE_BUILD_NUM
            docker push siddokit/webapp:latest
          working_directory: ./src
      - run:
          name: Deploy on server
          command: |            
            echo Complite release number  $CIRCLE_BUILD_NUM 
            ssh -o "StrictHostKeyChecking=no"  $user@$host sh ./clean.sh
            ssh -o "StrictHostKeyChecking=no"  $user@$host docker run -d --name webapi1 -p 80:80 -p 433:433 $DOCKER_LOGIN/webapp:0.0.$CIRCLE_BUILD_NUM
            
workflows:
  version: 2
  build:
    jobs:
      - buildAndPush

