version: '3.4'

services:
  webapp:
    build:
      context: .
      dockerfile: webapp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    command: dotnet dev-certs https --clean
    command: dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p 12345
    command: dotnet dev-certs https --trust

    ports:
      - "80"
      - "443"
    